-- Seed: the dictionary's 12 HVAC equipment types as AssetCategory rows (rule 13)
-- Generated by sql/forms/generate_form_seed.py on 2026-09-06 from Universal_HVAC_PM_Master_Checklist_Data_Dictionary.xlsx (Dropdown Lists).
-- Do not hand-edit: change the workbook or the generator and regenerate.
-- Requires create_form_tables.sql. Safe to re-run (see the notes in each block).

-- Existing HVAC categories (Chiller, Energy Management System, Exhaust Fan, Hood Vent, HVAC, Thermostat) are left untouched.
-- Required-field flags follow the existing HVAC rows (manufacturer, model, serial, description all required).
SET NOCOUNT ON;
DECLARE @t_id INT = (SELECT TOP 1 t_id FROM dbo.Trade WHERE t_trade = N'HVAC' AND t_id_parent IS NULL);
IF @t_id IS NULL BEGIN RAISERROR('Parent trade HVAC not found', 16, 1); RETURN; END;
DECLARE @inserted INT = 0;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'RTU'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'RTU', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Split System'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Split System', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'AHU'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'AHU', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Heat Pump'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Heat Pump', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Water-Source Heat Pump'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Water-Source Heat Pump', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'VAV'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'VAV', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'FPVAV'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'FPVAV', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Fan Coil'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Fan Coil', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'VRF'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'VRF', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Exhaust / Booster Fan'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Exhaust / Booster Fan', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Refrigeration'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Refrigeration', 1, 1, 1, 1);
    SET @inserted += 1;
END;
IF NOT EXISTS (SELECT 1 FROM dbo.AssetCategory WHERE t_id = @t_id AND LOWER(LTRIM(RTRIM(asc_category))) = LOWER(N'Other'))
BEGIN
    INSERT INTO dbo.AssetCategory (t_id, asc_category, asc_manufacturer, asc_modelnumber, asc_serialnumber, asc_description)
        VALUES (@t_id, N'Other', 1, 1, 1, 1);
    SET @inserted += 1;
END;
PRINT 'HVAC asset categories inserted: ' + CAST(@inserted AS VARCHAR(10));
